### ISSUE TITLE
suggestion: use auto-value-parcel/-gson/-with

### ISSUE THREAD

**Issue by Rainer-Lang** [cavarzan/generator-android-hipster#18]
auto-value-parcel -> https://github.com/rharter/auto-value-parcel
auto-value-gson -> https://github.com/rharter/auto-value-gson
auto-value-with -> https://github.com/gabrielittner/auto-value-with

**Comment by cavarzan** [comment]
@Rainer-Lang Indeed, since auto now supports extensions, I need to migrate. I'm currently using the rharter projects now.
